package com.my.workmanagerdemo1

const val KEY_ONE_TIME_WORK_1_RESULT_1 = "KEY_ONE_TIME_WORK_1_RESULT_1"
const val KEY_ONE_TIME_WORK_1_RESULT_2 = "KEY_ONE_TIME_WORK_1_RESULT_2"

const val KEY_PERIOD_WORK_1_RESULT_1 = "KEY_PERIOD_WORK_1_RESULT_1"
const val KEY_PERIOD_WORK_1_RESULT_2 = "KEY_PERIOD_WORK_1_RESULT_2"

const val KEY_NO_LIMIT_WORK_1_RESULT_1 = "KEY_NO_LIMIT_WORK_1_RESULT_1"
const val KEY_NO_LIMIT_WORK_1_RESULT_2 = "KEY_NO_LIMIT_WORK_1_RESULT_2"

const val NO_LIMIT_WORK_1 = "NO_LIMIT_WORK_1"
const val NO_LIMIT_WORK_2 = "NO_LIMIT_WORK_2"
const val ONE_TIME_WORK_1 = "ONE_TIME_WORK_1"